[package]
name = "tsr"
version = "0.1.4"
edition = "2021"

[profile.release]
debug = 0

[features]
default = ["index_sort", "log"]
index_sort = []
lru_cache = []
auto_index = []
allow_ip = []
block_ip = []
log = []

[dependencies]
async-mutex = "1.4.0"
chrono = { version = "0.4.38", features = ["clock", "now"] }
clap = { version = "4.5.7", features = ["derive"] }
env_logger = { version = "0.11.3", features = ["color"] }
lazy_static = "1.4.0"
log = { version = "0.4.21" }
lru = "0.12.3"
mime = { version = "0.3.17" }
mime_guess = { version = "2.0.4" }
serde = { version = "1.0.203", features = ["derive"] }
serde_yaml = "0.9.34"
tokio = { version = "1.38.0", features = [
    "rt",
    "rt-multi-thread",
    "fs",
    "io-std",
    "io-util",
    "net",
    "macros",
] }
